<a href="https://colab.research.google.com/github/stevengregori92/LearnRecSys/blob/main/Demographic_Filtering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
!gdown https://drive.google.com/uc?id=1kF6d9bJnZjehyPeoh6ixMETJnYbjFC3I
!unzip /content/rec.zip

Downloading...
From: https://drive.google.com/uc?id=1kF6d9bJnZjehyPeoh6ixMETJnYbjFC3I
To: /content/rec.zip
100% 18.1M/18.1M [00:00<00:00, 92.2MB/s]
Archive:  /content/rec.zip
  inflating: collaborative_filtering.csv
  inflating: content_by_multiple.csv
  inflating: content_by_synopsis.csv
  inflating: demographic.csv

#Filtering -> Scoring -> Sort

In [4]:
df = pd.read_csv('demographic.csv')
df

,title,genres,runtime,vote_average,vote_count,release_year,Action,Adventure,Animation,Comedy,...,History,Horror,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western
0,Toy Story,Animation; Comedy; Family,81.0,7.7,5415.0,1995,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,Jumanji,Adventure; Fantasy; Family,104.0,6.9,2413.0,1995,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Grumpier Old Men,Romance; Comedy,101.0,6.5,92.0,1995,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
3,Waiting to Exhale,Comedy; Drama; Romance,127.0,6.1,34.0,1995,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
4,Father of the Bride Part II,Comedy,106.0,5.7,173.0,1995,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45125,Robin Hood,Drama; Action; Romance,104.0,5.7,26.0,1991,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
45126,Century of Birthing,Drama,360.0,9.0,3.0,2011,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45127,Betrayal,Action; Drama; Thriller,90.0,3.8,6.0,2003,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
45128,Satan Triumphant,NaN,87.0,0.0,0.0,1917,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45129,Queerama,NaN,75.0,0.0,0.0,2017,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
df.sort_values('vote_average', ascending=False)

,title,genres,runtime,vote_average,vote_count,release_year,Action,Adventure,Animation,Comedy,...,History,Horror,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western
30718,Mortal Kombat: The Journey Begins,Action; Animation,54.0,10.0,1.0,1995,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
31691,Canal Zone,Documentary,174.0,10.0,1.0,1977,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
44549,Lad: A Yorkshire Story,NaN,96.0,10.0,1.0,2013,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37671,Bowery Battalion,Comedy,69.0,10.0,1.0,1951,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
43186,Firefly,Comedy,84.0,10.0,1.0,1975,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32120,The Collection,NaN,64.0,0.0,0.0,1976,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21585,The Wet Parade,Drama; History; Romance,118.0,0.0,1.0,1932,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
21582,The Story of Maths,Documentary,240.0,0.0,0.0,2008,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21537,Setouchi Moonlight Serenade,Drama,117.0,0.0,0.0,1997,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45129,Queerama,NaN,75.0,0.0,0.0,2017,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

#Step 1: Filter

In [6]:
genre = ['Animation']
duration = (60, 150)
year = (2000, 2019)
topk = 20

In [7]:
df = df[df.release_year.between(year[0], year[1]) &
        df.runtime.between(duration[0], duration[1]) &
        df[genre].all(axis=1)]
df

,title,genres,runtime,vote_average,vote_count,release_year,Action,Adventure,Animation,Comedy,...,History,Horror,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western
3161,The Tigger Movie,Animation; Family,77.0,6.3,146.0,2000,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3354,The Road to El Dorado,Adventure; Animation; Comedy; Family,89.0,7.0,892.0,2000,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
3484,Dinosaur,Animation; Family,82.0,6.2,563.0,2000,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3614,Titan A.E.,Animation; Action; Science Fiction; Family; Ad...,94.0,6.3,320.0,2000,1,1,1,0,...,0,0,0,0,0,1,0,0,0,0
3619,Chicken Run,Animation; Comedy; Family,84.0,6.5,1190.0,2000,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44829,Enchiridion,Animation; Horror; Drama,81.0,0.0,0.0,2012,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
44848,Nerdland,Animation,83.0,5.8,11.0,2016,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
44865,The Dragon Spell,Family; Comedy; Animation; Fantasy; Adventure,85.0,4.0,1.0,2017,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
44909,Sahara,Adventure; Animation; Comedy; Family,86.0,5.4,43.0,2017,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
45114,Pooh's Heffalump Halloween Movie,Animation; Family,67.0,5.4,7.0,2005,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

#Step 2: Scoring
gunakan vote_average sebagai scoring

#Step 3: Sort

In [9]:
recommendation = df.loc[:, 'title': 'release_year']
recommendation = recommendation.sort_values('vote_average', ascending = False).head(topk)
recommendation

,title,genres,runtime,vote_average,vote_count,release_year
25671,Rocks in my Pockets,Comedy; Animation; Drama,88.0,9.4,5.0,2014
41890,Kizumonogatari Part 3: Reiketsu,Animation; Fantasy; Mystery,82.0,9.4,5.0,2017
26636,Lotte from Gadgetville,Adventure; Animation; Comedy; Family,81.0,9.0,4.0,2006
41846,Kizumonogatari Part 2: Nekketsu,Animation; Fantasy; Mystery,68.0,8.9,11.0,2016
35577,"Fuse, Memoirs of the Hunter Girl",Action; Animation; Drama; History,110.0,8.8,4.0,2012
43038,In This Corner of the World,Animation; Drama,128.0,8.7,19.0,2016
40018,Your Name.,Romance; Animation; Drama,106.0,8.5,1030.0,2016
28618,The Life and Mind of Mark DeFriest,Animation; Documentary,92.0,8.5,2.0,2014
41695,The Snow Queen 3: Fire and Ice,Family; Animation; Fantasy,80.0,8.5,2.0,2016
26159,The Littlest Angel,Animation; Family,84.0,8.5,2.0,2011
5471,Spirited Away,Fantasy; Adventure; Animation; Family,125.0,8.3,3968.0,2001
16754,Corto Maltese: Under the Sign of Capricorn,Adventure; Animation; Action,85.0,8.3,4.0,2002
40531,The Girl Without Hands,Animation,76.0,8.3,5.0,2016
31851,The Crisis of Civilization,Documentary; Animation; History,82.0,8.3,2.0,2012
40238,Over the Garden Wall,Adventure; Animation; Family; Fantasy,110.0,8.2,52.0,2014
9687,Howl's Moving Castle,Fantasy; Animation; Adventure,119.0,8.2,2049.0,2004
29095,Cheatin',Animation,72.0,8.2,10.0,2013
42373,My Entire High School Sinking Into the Sea,Animation,75.0,8.2,3.0,2016
24971,Song of the Sea,Family; Animation; Fantasy,93.0,8.1,420.0,2014
28741,The Garden of Sinners - Chapter 5: Paradox Spiral,Action; Animation; Drama; Mystery; Thriller,114.0,8.1,15.0,2008